version: '3'

services:
  api:
    build: api/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: rect_detect_api

  ui:
    build: ui/
    depends_on:
      - api
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: rect_detect_ui

networks:
  deploy_network:
    driver: bridge